<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [3]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [20]:
%%sql
select *
from currencyExchange
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

         date fromcurrency tocurrency  exchange
0  2015-01-01          AUD        AUD      1.00
1  2015-01-01          AUD        CAD      0.95
2  2015-01-01          AUD        EUR      0.67
3  2015-01-01          AUD        GBP      0.53
4  2015-01-01          AUD        USD      0.82
5  2015-01-01          CAD        AUD      1.05
6  2015-01-01          CAD        CAD      1.00
7  2015-01-01          CAD        EUR      0.71
8  2015-01-01          CAD        GBP      0.55
9  2015-01-01          CAD        USD      0.86

In [28]:
%%sql
select date, exchange
from currencyExchange
where tocurrency = 'EUR' and fromcurrency = 'USD'
ORDER BY date	 DESC
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

         date  exchange
0  2024-12-31      0.92
1  2024-12-30      0.93
2  2024-12-29      0.92
3  2024-12-28      0.93
4  2024-12-27      0.93
5  2024-12-26      0.93
6  2024-12-25      0.93
7  2024-12-24      0.93
8  2024-12-23      0.92
9  2024-12-22      0.92